CREATE TABLE user (FIRSTNAME VARCHAR(64), LASTNAME VARCHAR(64), EMAIL VARCHAR(64));

INSERT INTO user (FIRSTNAME VARCHAR(64), LASTNAME VARCHAR(64), EMAIL VARCHAR(64))
VALUES ("Mateusz", "Jezierski", "mateuszjezierski@wp.eu");